sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df4440290bd89d941fb4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  email: false
