sudo: false
language: node_js
cache:
  directories:
    - node_modules
before_script:
  - npm prune
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df4440290bd89d941fb4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  email: false
script:
  - npm run test-ci
addons:
  sauce_connect:
    username: ampersandjs-ci
    access_key:
      secure: "gd/90cxn7Z9li+nKDKTxuKizhCdL2LdRd1fiPuK8oEgRRNXAYnQzmY9Gw9DUjDPPsW5VtBWKdRcADJhzQcumTwGu34+m0GL7JK8H5Wcmu4JBlSP68kTXNOvONVe4jCwLZmllMV6fxiVDRxHAgCKniaOL1L+crn+zx5eBSDrTITQ="
