ui: tape
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: '8.4..latest'
  - name: android
    version: '4.4..latest'
